artifact_location: file:///C:/Users/maxmo/Documents/Max/multimodal_detector/runs/mlflow/327915664936175339
creation_time: 1776411406279
experiment_id: '327915664936175339'
last_update_time: 1776411406279
lifecycle_stage: active
name: multimodal_detector
trace_location: null
workspace: default
