dataset:
  pc_range: [0, -39.68, -3, 69.12, 39.68, 1]
  grid_size: [432, 496]
  data_path: "./data/kitti_lidar"
  num_channels: 3
train_params:
  workers: 2         
  batch: 16         
  epochs: 10
  optimizer: "AdamW"
  lr: 0.0001       
  weight_decay: 0.01  
  patience: 10        
  save: True          
  cache: True   
  exist_ok: True
experiment_name: "multimodal_detector_lidar"
run_name: "First Tests LiDAR"
model_variant: "PillarBackbone"